### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by chocopops2x** [admin-else/Minescanner#1]

**Comment by admin-else** [comment]
umm i dont really know but i think you can try to

1. clone the repo
2. run the src/Scraper.py
3. copy + paste the errors that it gives into chat gpt and do what it says
4. if there is a fatal error do step 3 with that error


ye that schould work but umm
NOTE: may only work on linux
NOTE NOTE: its abandoned
NOTE NOTE NOTE: if you wanna fork it do so..

**Comment by Cabbasca** [comment]
learn coding

**Comment by chocopops2x** [comment]
> learn coding

I know coding.

**Comment by Cabbasca** [comment]
lol it's chopops

**Comment by Cabbasca** [comment]
you don't know coding if you can't run this shitty python program

**Comment by Cabbasca** [comment]
I got the Benz and got beef, finna cook it (err)
Big flawless diamonds, bitch, they sit on my wrist (ooh)
They said they wan' sign a lil' kid for some cheese (noble, this is crazy)
I told 'em it's "Fuck 'em, I'm already rich" (rich)
