### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Visivel** [admin-else/Minescanner#2]
put a requirements txt cuz im too lazy to download all that (and discover what i gotta to install)

**Comment by Cabbasca** [comment]
no

**Comment by Cabbasca** [comment]
minescanner is not meant to be ran by anyone except for admin else because he is the only one who understands the horrible code and what you need to run it (it only works on his machine pretty much)

**Comment by Visivel** [comment]
> minescanner is not meant to be ran by anyone except for admin else because he is the only one who understands the horrible code and what you need to run it (it only works on his machine pretty much)

true lol, then why he posts his stuff on github?

**Comment by admin-else** [comment]
i dont know lmao
